spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_react?serverTimezone=UTC&useSSL=false
    username: root
    password:
  flyway:
    url: jdbc:mysql://localhost:3306?serverTimezone=UTC&useSSL=false
    user: root
    password:
    schemas: spring_react
    clean-disabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
  main:
    banner-mode: "off"
  test:
    database:
      replace: none
