spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_react?serverTimezone=UTC&useSSL=false
    username: root
    password:
  flyway:
    url: jdbc:mysql://localhost:3306?serverTimezone=UTC&useSSL=false
    user: root
    password:
    schemas: spring_react
    clean-disabled: true
